version: 2.0.{build}
branches:
  only:
  - master
os:
  - Visual Studio 2017
assembly_info:
  patch: true
  file: '**\RuskinDantra.Extensions.csproj'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: 
  - dotnet restore Extensions.sln
test_script:
  - dotnet test .\RuskinDantra.Extensions.UnitTests\RuskinDantra.Extensions.UnitTests.csproj
after_build:
  - nuget pack RuskinDantra.Extensions\RuskinDantra.Extensions.nuspec -Version %appveyor_build_version%
  - appveyor PushArtifact RuskinDantra.Extensions.%appveyor_build_version%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: Kf0y949WcybDLqUPuqRxOJaEcDod3fdJFTgCBGTB17TM2UWYbXKZuT1s23ZZ3snp
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/